version: '3.3'

services:
  redis:
    container_name: redis
    build:
      context: .
      dockerfile: redis_configs/Dockerfile
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/root/redis
      - ./redis_configs/redis.conf:/usr/local/etc/redis/redis.conf

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped
    environment:
      - RI_HOST=redis
