version: "3"
services: 
    db:
        container_name: porstgres_db
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=sonar
        volumes:
            - postgresql_db:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data 

volumes:
    postgresql_data:
    postgresql_db:
